apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    # IMPORTANT: This must match the labels on your node-exporter pods
    app: node-exporter 
  ports: 
    - name: metrics
      port: 9100
      targetPort: 9100


