apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "kepler-pods"
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: kepler
         
          - action: keep
            source_labels: [__meta_kubernetes_pod_name]
            regex: kepler.*


          - action: replace
            source_labels: [__meta_kubernetes_pod_ip]
            regex: (.+)
            target_label: __address__
            replacement: $1:28282

 
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: instance

      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - node-exporter.monitoring.svc.cluster.local:9100
